version: '2'

services:
  app:
    container_name: app
    image: rest-api-restaurant-bussines:latest
    #        image: 00313/docker-spring-boot-postgres:latest
    build:
      context: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_DATASOURCE_INITIALIZE=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_HIBERNATE_SHOW_SQL=true
      - SPRING_HIBERNATE_FORMAT_SQL=true
      - SPRING_JACKSON_SERIALIZATION_FAIL_ON_EMPTY_BEANS=false

  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data
