version: '3.9'

services:
  app:
    container_name: app-spring-boot
    image: rest-api-restaurant-bussines:latest
    build:
      context: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_SHOW_SQL=true
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_DATASOURCE_INITIALIZE=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_HIBERNATE_SHOW_SQL=true
#      - SPRING_HIBERNATE_FORMAT_SQL=true
      - SPRING_JACKSON_SERIALIZATION_FAIL_ON_EMPTY_BEANS=false
      - TOKEN.SIGNING.KEY=53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855


  db:
    container_name: db-2
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
    volumes:
      #      - ./data/postgres:/docker-entrypoint-initdb.d
      - ./data/postgres:/var/lib/postgresql/data
